### ISSUE TITLE
Compile error: stx/btree_map.h: No such file or directory

### ISSUE THREAD

**Issue by baotonglu** [zxjcarrot/DPTree-code#2]
When I compile the code (GCC 10.2), it has the compile error "stx/btree_map.h: No such file or directory". 
Could you take a look how to fix it?

**Comment by zxjcarrot** [comment]
Hi baotong,

I have updated the README for how to compile the code and fixed several compilation issues. 

Thanks for the feedback.

**Comment by baotonglu** [comment]
Thanks!
